dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
services:
  - cassandra
sudo: required

install:
  - PATH=$PATH:/home/travis/.cargo/bin

script:
  #   - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose --no-fail-fast
  - cargo test --verbose --no-fail-fast --features e2e-tests
  - cargo test --no-fail-fast --features ssl
