[package]
name = "cdrs"
version = "1.0.0-beta.5"
authors = ["Alex Pikalov <alex.pikalov.khar@gmail.com>"]

description = "Cassandra DB driver written in Rust"
documentation = "https://docs.rs/cdrs"
homepage = "https://github.com/AlexPikalov/cdrs"
repository = "https://github.com/AlexPikalov/cdrs"
readme = "./README.md"
keywords = ["cassandra", "driver", "client", "cassandradb", "DB"]
license = "MIT/Apache-2.0"

[features]
default = []
ssl = ["openssl"]

[dependencies]
byteorder = "0.5.3"
log = "0.3.6"
uuid = "0.2"
snap = "0.1.2"
lz4-compress = "0.1.0"
r2d2 = "0.7.1"
openssl = { version = "0.9.6", optional = true }

[dev-dependencies]
env_logger = "0.3"
