[package]
name = "cdrs"
version = "0.1.0"
authors = ["Alex Pikalov <alex.pikalov.khar@gmail.com>"]

description = "Cassandra DB driver written in Rust"
documentation = "https://alexpikalov.github.io/cdrs/cdrs/index.html"
homepage = "https://github.com/AlexPikalov/cdrs"
repository = "https://github.com/AlexPikalov/cdrs"
readme = "https://github.com/AlexPikalov/cdrs/blob/master/README.md"
keywords = ["cassandra", "driver", "client", "cassandradb", "DB"]
license = "MIT"
license-file = "https://github.com/AlexPikalov/cdrs/blob/master/license.txt"

[dependencies]
byteorder = "0.5.3"
log = "*"
uuid = "0.2"
snap = "0.1.2"
lz4-compress = "0.1.0"
