[package]
name = "cdrs"
version = "0.1.0"
authors = ["Alex Pikalov <alex.pikalov.khar@gmail.com>"]

[dependencies]
byteorder = "0.5.3"
log = "*"
tokio-core = "0.1.0"
futures = "0.1.3"
# tokio-core = {git="https://github.com/tokio-rs/tokio-core.git"}
# futures = {}
