[package]
name = "cdrs"
version = "1.0.0"
authors = ["Alex Pikalov <alex.pikalov.khar@gmail.com>"]

description = "Cassandra DB driver written in Rust"
documentation = "https://docs.rs/cdrs"
homepage = "https://github.com/AlexPikalov/cdrs"
repository = "https://github.com/AlexPikalov/cdrs"
readme = "./README.md"
keywords = ["cassandra", "driver", "client", "cassandradb", "DB"]
license = "MIT/Apache-2.0"

[features]
default = ["v4"]
ssl = ["openssl"]
v3 = []
v4 = []
# enable v5 feature when it's actually implemented
# v5 = []
appveyor = []

[dependencies]
byteorder = "0.5.3"
log = "0.3.6"
lz4-compress = "=0.1.0"
openssl = { version = "0.9.6", optional = true }
r2d2 = "0.7.1"
rand = "0.3"
snap = "0.2"
time = "0.1.36"
uuid = "0.5.0"

[dev-dependencies]
env_logger = "0.3"
maplit = "0.1.4"
regex = "0.2.1"
