[package]
name = "cdrs"
version = "1.2.2"
authors = ["Alex Pikalov <alex.pikalov.khar@gmail.com>"]

description = "Cassandra DB driver written in Rust"
documentation = "https://docs.rs/cdrs"
homepage = "https://github.com/AlexPikalov/cdrs"
repository = "https://github.com/AlexPikalov/cdrs"
readme = "./README.md"
keywords = ["cassandra", "driver", "client", "cassandradb", "DB"]
license = "MIT/Apache-2.0"

[features]
default = ["v4"]
ssl = ["openssl"]
v3 = []
v4 = []
# enable v5 feature when it's actually implemented
# v5 = []
appveyor = []

[dependencies]
byteorder = "1.2.1"
log = "0.4.1"
lz4-compress = "=0.1.0"
openssl = { version = "0.9.23", optional = true }
r2d2 = "0.8.2"
rand = "0.4.1"
snap = "0.2.3"
time = "0.1.38"
uuid = "0.6.1"

[dev-dependencies]
env_logger = "0.4.3"
maplit = "1.0.0"
regex = "0.2.5"
