[package]
name = "cdrs"
version = "0.4.1"
authors = ["Alex Pikalov <alex.pikalov.khar@gmail.com>"]

description = "Cassandra DB driver written in Rust"
documentation = "https://docs.rs/cdrs"
homepage = "https://github.com/AlexPikalov/cdrs"
repository = "https://github.com/AlexPikalov/cdrs"
readme = "./README.md"
keywords = ["cassandra", "driver", "client", "cassandradb", "DB"]
license = "MIT"

[dependencies]
byteorder = "0.5.3"
log = "0.3.6"
uuid = "0.2"
snap = "0.1.2"
lz4-compress = "0.1.0"
